dependencies {
 api("com.github.GTNewHorizons:AE2FluidCraft-Rework:1.5.106-gtnh:dev")
 api('com.github.GTNewHorizons:GT5-Unofficial:5.09.54.133:dev')
api("com.github.GTNewHorizons:Applied-Energistics-2-Unofficial:rv3-beta-1050-GTNH:dev")


   //api('com.github.GTNewHorizons:GT5-Unofficial:5.09.52.190:dev')
    api rfg.deobf("curse.maven:thaumcraft-nei-plugin-225095:2241913")

  //api("com.github.GTNewHorizons:StructureLib:1.4.42:dev")
    api("net.industrial-craft:industrialcraft-2:2.2.828-experimental:dev")
    api("com.github.GTNewHorizons:NotEnoughItems:2.8.130-GTNH:dev")
    //api("com.github.GTNewHorizons:NotEnoughIds:2.1.11:dev")
    api("com.github.GTNewHorizons:GTNHLib:0.11.46:dev")

    api("com.github.GTNewHorizons:ModularUI2:2.3.88-1.7.10:dev")
    compileOnly rfg.deobf("curse.maven:neverenoughanimation-1062347:6552319")


    api("com.github.GTNewHorizons:waila:1.19.34:dev")
    
    api('com.github.GTNewHorizons:Yamcl:0.7.5:dev')
    api("com.github.GTNewHorizons:Postea:1.2.6:dev")

    compileOnlyApi('com.github.GTNewHorizons:ThaumicTinkerer:2.12.32:dev')
    compileOnlyApi("com.github.GTNewHorizons:Mobs-Info:0.5.21-GTNH:dev")
    //api("com.github.GTNewHorizons:Navigator:1.1.4:dev")
    //api('com.github.GTNewHorizons:Baubles:1.0.4:dev') {transitive=false}
	api('com.github.GTNewHorizons:Baubles-Expanded:2.2.22-GTNH:dev') {transitive=false}
    // Required to prevent an older bauble api from Extra Utilities from loading first in the javac classpath
   // compileOnly('com.github.GTNewHorizons:Baubles:1.0.4:dev') {transitive=false}

    devOnlyNonPublishable("com.github.GTNewHorizons:Infernal-Mobs:1.10.6-GTNH:dev")

    api("com.github.GTNewHorizons:Avaritia:1.99:dev")
	api("com.github.GTNewHorizons:Avaritiaddons:1.9.6-GTNH:dev")
    api('com.github.GTNewHorizons:Angelica:2.2.10:api') { transitive = false }
    //api("com.github.GTNewHorizons:AppleCore:3.3.11:dev") { transitive = false }
    api("com.github.GTNewHorizons:BuildCraft:7.1.63:dev") { transitive = false }
    api("com.github.GTNewHorizons:EnderIO:2.10.44:dev") { transitive = true }
    //api("com.github.GTNewHorizons:ForestryMC:4.11.31:dev") { transitive = false }
    api("com.github.GTNewHorizons:ProjectRed:4.12.43-GTNH:dev") { transitive = false }
    api("com.github.GTNewHorizons:Railcraft:9.17.31:dev") { transitive = false }

    //compileOnly("TGregworks:TGregworks:1.7.10-GTNH-1.0.26:deobf") {transitive = false}
    compileOnly("com.github.GTNewHorizons:ThaumicBases:1.9.19:dev") { transitive = false }
    api("com.github.GTNewHorizons:EnderCore:0.5.15:dev") { transitive = false }
    compileOnly('com.github.GTNewHorizons:VisualProspecting:1.5.39:dev') { transitive = false }
   // api("com.github.GTNewHorizons:Galaxy-Space-GTNH:1.1.139-GTNH:dev") { transitive = false }

    api("com.github.GTNewHorizons:Galacticraft:3.4.33-GTNH:dev") { transitive = false }
    api("com.github.GTNewHorizons:TinkersConstruct:1.14.108-GTNH:dev")

    api("com.github.GTNewHorizons:Chisel:2.17.32-GTNH:dev") { transitive = false }
    api("com.github.GTNewHorizons:Translocators:1.4.5:dev") { transitive = false }
    api rfg.deobf("curse.maven:cofh-core-69162:2388751")
    api("com.github.GTNewHorizons:Nuclear-Control:2.7.13:dev") { transitive = false }
    api("thaumcraft:Thaumcraft:1.7.10-4.2.3.5:dev") { transitive = false }
    api("com.github.GTNewHorizons:Hodgepodge:2.7.196:dev")
    //api('com.github.GTNewHorizons:Botania:1.13.26-GTNH:dev') { transitive = false }
    api('com.github.GTNewHorizons:HoloInventory:2.5.17-GTNH:dev') { transitive = false }
    api rfg.deobf("curse.maven:extra-utilities-225561:2264384")
    compileOnly rfg.deobf('curse.maven:minefactory-reloaded-66672:2366150')
    api("com.github.GTNewHorizons:OpenComputers:1.12.61-GTNH:dev") {transitive = false}
     api("com.github.GTNewHorizons:Computronics:1.9.10-GTNH:dev")

    api rfg.deobf('curse.maven:advsolar-362768:2885953')

    api("com.github.GTNewHorizons:BloodMagic:1.9.13:dev") { transitive = false }
    api("com.github.GTNewHorizons:CraftTweaker:3.4.8:dev") { transitive = false }
    compileOnly("com.github.GTNewHorizons:BetterLoadingScreen:1.7.16-GTNH:dev") { transitive = false }
    compileOnly rfg.deobf("curse.maven:biomes-o-plenty-220318:2499612")

    compileOnly('com.github.GTNewHorizons:SC2:2.3.15:dev') {transitive=false}
    compileOnly('com.github.GTNewHorizons:Binnie:2.6.47:dev') {transitive = false}
    api('curse.maven:PlayerAPI-228969:2248928') {transitive=false}
    api('com.github.GTNewHorizons:BlockRenderer6343:1.4.21:dev'){transitive=false}

    compileOnly("com.google.auto.value:auto-value-annotations:1.10.1") { transitive = false }
    annotationProcessor("com.google.auto.value:auto-value:1.10.1")



 api("com.github.GTNewHorizons:NotEnoughEnergistics:1.7.41:dev")


	api("com.github.GTNewHorizons:ForgeMultipart:1.7.12:dev") { transitive = false }



	  api('com.github.GTNewHorizons:ThaumicEnergistics:1.7.60-GTNH:dev')

	api("com.github.GTNewHorizons:MrTJPCore:1.3.7:dev")

	 //api('com.github.GTNewHorizons:Navigator:1.1.4:dev')
     runtimeOnlyNonPublishable(rfg.deobf('maven.modrinth:journeymap:5.2.6'))


	  api("com.github.GTNewHorizons:ironchest:6.1.13:dev")
    api("com.github.GTNewHorizons:RemoteIO:2.7.10:dev")


   api("com.github.GTNewHorizons:ForgeRelocation:0.3.7:dev")


  api("com.github.GTNewHorizons:BetterP2P:1.4.7:dev")


	  api("com.github.GTNewHorizons:CodeChickenCore:1.4.19:dev")

}
 configurations.configureEach {
    exclude group: 'com.github.GTNewHorizons', module: 'CodeChickenLib'
    exclude group: 'com.github.GTNewHorizons', module: 'Baubles'
    

    //this is out-dated and crashes the game, so exclude it.
    //CCCore is enough
     exclude group: 'com.github.GTNewHorizons', module: 'NotEnoughIDs'
}