name: Build and test

on:
  workflow_dispatch:
    inputs:
      workspace:
        description: 'setupCIWorkspace/setupDecompWorkspace'
        required: false
        default: "setupCIWorkspace"
        type: string
  pull_request:
    branches: [ "*" ]
  push:
    branches: [ "*" ]

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test-x.yml
    secrets: inherit
    